[package]
name = "obscura-embedder"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
cookie = { workspace = true }
servo = { path = "../../servo/components/servo", default-features = false, features = ["bundled", "webcrypto"] }
url.workspace = true
dpi.workspace = true
euclid.workspace = true
keyboard-types = "0.8.3"
log.workspace = true
serde.workspace = true
serde_json.workspace = true
http.workspace = true
image.workspace = true
tokio = { workspace = true, features = ["rt", "net", "macros"] }
tokio-tungstenite.workspace = true
futures-util = "0.3"
base64.workspace = true

[features]
default = []
