[package]
name = "obscura-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "obscura"
path = "src/main.rs"

[features]
default = []
stealth = ["obscura-net/stealth"]

[dependencies]
obscura-embedder = { workspace = true }
obscura-mcp = { workspace = true }
obscura-net = { workspace = true }
tokio = { workspace = true }
clap = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
url = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
image = { version = "0.25", default-features = false, features = ["png"] }
